import type { Metadata } from "next";
import "react-day-picker/dist/style.css";
import "./globals.css";


export const metadata: Metadata = {
  title: "TS.BS Chế Đình Nghĩa — Tư vấn CTCH Online",
  //description: "Generated by create next app",
};

export default function RootLayout(
  {children}: Readonly<{children: React.ReactNode;}>
) 
{
  return (
    <html
      lang="vi"
    >
      <body className="min-h-full flex flex-col">
          {children}
      </body>
    </html>
  );
}
